export const BATTLE_STATUS_WAITING_FAST = 'WAITING_FAST';
export const BATTLE_STATUS_START_FAST = 'START_FAST';
export const BATTLE_STATUS_CANCELED_FAST = 'CANCELED_FAST';
export const BATTLE_STATUS_ERROR_FAST = 'ERROR_FAST';
export const BATTLE_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const BATTLE_STATUS_CLOSED = 'CLOSED';