export const CHALLENGE_STATUS_START = 'START';
export const CHALLENGE_STATUS_END_TASK = 'END_TASK';
export const CHALLENGE_STATUS_NEXT_TASK = 'NEXT_TASK';
export const CHALLENGE_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const CHALLENGE_STATUS_CLOSED = 'CLOSED';

export const MAX_CHALLENGE_FRIENDS = 7;