export const CHALLENGE_STATUS_START = 'START';
export const CHALLENGE_STATUS_END_TASK = 'END_TASK';
export const CHALLENGE_STATUS_NEXT_TASK = 'NEXT_TASK';
export const CHALLENGE_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const CHALLENGE_STATUS_CLOSED = 'CLOSED';

export const MAX_CHALLENGE_FRIENDS = 7;

export const CHALLENGE_ACCESS_LOCK = 'LOCK';
export const CHALLENGE_ACCESS_UNLOCK = 'UNLOCK';
export const CHALLENGE_ACCESS_INVITE = 'INVITE';

export const CHALLENGE_APPROACH_ONE = 'ONE';
export const CHALLENGE_APPROACH_MANY = 'MANY';

export const CHALLENGE_RESOURCE_COST_0 = 0;
export const CHALLENGE_RESOURCE_COST_1 = 1;
export const CHALLENGE_RESOURCE_COST_5 = 5;
export const CHALLENGE_RESOURCE_COST_10 = 10;

export const CHALLENGE_DURATION_4 = 4;
export const CHALLENGE_DURATION_8 = 8;
export const CHALLENGE_DURATION_24 = 24;
export const CHALLENGE_DURATION_48 = 48;