export const WAITING_FOR_QUESTION = 'WAITING_FOR_QUESTION';
export const READING_QUESTION = 'READING_QUESTION';
export const THINKING = 'THINKING';
export const THINK_KNOW_ANSWER = 'THINK_KNOW_ANSWER';
export const SEARCHING_FOR_ANSWER = 'SEARCHING_FOR_ANSWER';
export const ANSWERED = 'ANSWERED';