export const WAITING_FOR_QUESTION = 'WAITING_FOR_QUESTION';
export const READING_QUESTION = 'READING_QUESTION';
export const THINKING = 'THINKING';

export const THINK_KNOW_ANSWER = 'THINK_KNOW_ANSWER';
export const LOOKING_FOR_ANSWER = 'LOOKING_FOR_ANSWER';

export const NO_FOUND_ANSWER_LOOKING_FOR = 'NO_FOUND_ANSWER_LOOKING_FOR';
export const FOUND_ANSWER_LOOKING_FOR = 'FOUND_ANSWER_LOOKING_FOR';

export const NOT_SURE_OF_ANSWER = 'NOT_SURE_OF_ANSWER';
export const READING_ANSWERS = 'READING_ANSWERS';

export const ANSWERED = 'ANSWERED';
export const SURRENDER = 'SURRENDER';

export const WILL_GIVE_RANDOM_ANSWER = 'WILL_GIVE_RANDOM_ANSWER';
export const WONT_GIVE_RANDOM_ANSWER = 'WONT_GIVE_RANDOM_ANSWER';

export const THINKING_WHICH_ANSWER_MATCH = 'THINKING_WHICH_ANSWER_MATCH';
export const THINKING_IF_GIVE_RANDOM_ANSWER = 'THINKING_IF_GIVE_RANDOM_ANSWER';


export const DREAMING_ABOUT_VACATION = 'DREAMING_ABOUT_VACATION';
export const SCRATCHING = 'SCRATCHING';
export const YAWNING = 'YAWNING';
export const HUNG_UP = 'HUNG_UP';
export const NEED_GO_TO_TOILET = 'NEED_GO_TO_TOILET';
