export const BATTLE_REQUIREMENT_LEVEL = 0;
export const BATTLE_FAST_REQUIREMENT_LEVEL = 3;
export const BATTLE_RANKING_REQUIREMENT_LEVEL = 4;
export const WAR_REQUIREMENT_LEVEL = 4;
export const WAR_FAST_REQUIREMENT_LEVEL = 5;
export const WAR_RANKING_REQUIREMENT_LEVEL = 5;
export const CHALLENGE_REQUIREMENT_LEVEL = 6;
export const CAMPAIGN_REQUIREMENT_LEVEL = 5;