import {
    TEXT_BATTLE,
    TEXT_BATTLE_OVER,
    TEXT_CAMPAIGN,
    TEXT_CAMPAIGN_OVER,
    TEXT_CHALLENGE,
    TEXT_CHALLENGE_OVER,
    TEXT_INVITE_TO_BATTLE,
    TEXT_INVITE_TO_WAR,
    TEXT_INVITED_TO_BATTLE_BY,
    TEXT_INVITED_TO_WAR_BY,
    TEXT_WAR,
    TEXT_WAR_OVER
} from "../lang/langText";
import {
    BATTLE_ROUTE,
    CAMPAIGN_WAR_ROUTE,
    CHALLENGE_ROUTE,
    CLASSIFICATION_BATTLE_ROUTE,
    CLASSIFICATION_WAR_ROUTE,
    WAR_ROUTE
} from "../content/routes";
import _ from 'lodash';

export const RIVAL_STATUS_START_FRIEND = 'START_FRIEND';
export const RIVAL_STATUS_CANCELED_FRIEND = 'CANCELED_FRIEND';
export const RIVAL_STATUS_ACCEPTED_FRIEND = 'ACCEPTED_FRIEND';
export const RIVAL_STATUS_REJECTED_FRIEND = 'REJECTED_FRIEND';
export const RIVAL_STATUS_ERROR_FRIEND = 'ERROR_FRIEND';
export const RIVAL_STATUS_INVITED_FRIEND = 'INVITED_FRIEND';

export const RIVAL_CONTENT_STATUS_INTRO = 'INTRO';
export const RIVAL_CONTENT_STATUS_PREPARING_NEXT_TASK = 'PREPARING_NEXT_TASK';
export const RIVAL_CONTENT_STATUS_CHOSEN_TASK_PROPS = 'CHOSEN_TASK_PROPS';
export const RIVAL_CONTENT_STATUS_ANSWERING = 'ANSWERING';
export const RIVAL_CONTENT_STATUS_ANSWERED = 'ANSWERED';
export const RIVAL_CONTENT_STATUS_ANSWERING_TIMEOUT = 'ANSWERING_TIMEOUT';
export const RIVAL_CONTENT_STATUS_CHOOSING_TASK_PROPS = 'CHOOSING_TASK_PROPS';
export const RIVAL_CONTENT_STATUS_CHOOSING_WHO_ANSWER = 'CHOOSING_WHO_ANSWER';
export const RIVAL_CONTENT_STATUS_CLOSED = 'CLOSED';

export const RIVAL_STATUS_START_RANDOM_OPPONENT = 'START_RANDOM_OPPONENT';
export const RIVAL_STATUS_CANCELED_RANDOM_OPPONENT = 'CANCELED_RANDOM_OPPONENT';
export const RIVAL_STATUS_ERROR_RANDOM_OPPONENT = 'ERROR_RANDOM_OPPONENT';
export const RIVAL_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const RIVAL_STATUS_CLOSED = 'CLOSED';

export const RIVAL_TYPE_BATTLE = 'BATTLE';
export const RIVAL_TYPE_WAR = 'WAR';
export const RIVAL_TYPE_CAMPAIGN_WAR = 'CAMPAIGN_WAR';
export const RIVAL_TYPE_CHALLENGE = 'CHALLENGE';

export const RIVAL_IMPORTANCE_FAST = 'FAST';
export const RIVAL_IMPORTANCE_RANKING = 'RANKING';

export const RIVAL_TYPE_INVITE_TEXT = {
    [RIVAL_TYPE_BATTLE]: TEXT_INVITE_TO_BATTLE,
    [RIVAL_TYPE_WAR]: TEXT_INVITE_TO_WAR,
};
export const RIVAL_TYPE_INVITED_TO_BY_TEXT = {
    [RIVAL_TYPE_BATTLE]: TEXT_INVITED_TO_BATTLE_BY,
    [RIVAL_TYPE_WAR]: TEXT_INVITED_TO_WAR_BY,
};
export const RIVAL_TYPE_WELCOME_MSG = {
    [RIVAL_TYPE_BATTLE]: TEXT_BATTLE,
    [RIVAL_TYPE_WAR]: TEXT_WAR,
    [RIVAL_TYPE_CAMPAIGN_WAR]: TEXT_CAMPAIGN,
    [RIVAL_TYPE_CHALLENGE]: TEXT_CHALLENGE,
};
export const RIVAL_TYPE_FAREWELL_MSG = {
    [RIVAL_TYPE_BATTLE]: TEXT_BATTLE_OVER,
    [RIVAL_TYPE_WAR]: TEXT_WAR_OVER,
    [RIVAL_TYPE_CAMPAIGN_WAR]: TEXT_CAMPAIGN_OVER,
    [RIVAL_TYPE_CHALLENGE]: TEXT_CHALLENGE_OVER,
};

export const ROUTE_RIVAL_TYPE = {
    [BATTLE_ROUTE]: RIVAL_TYPE_BATTLE,
    [WAR_ROUTE]: RIVAL_TYPE_WAR,
    [CAMPAIGN_WAR_ROUTE]: RIVAL_TYPE_CAMPAIGN_WAR,
    [CHALLENGE_ROUTE]: RIVAL_TYPE_CHALLENGE,
};

export const RIVAL_TYPE_ROUTE = _.reduce(ROUTE_RIVAL_TYPE, (acc, v, k) => {
    acc[v] = k;
    return acc;
}, {});

export const CLASSIFICATION_ROUTE_RIVAL_TYPE = {
    [CLASSIFICATION_BATTLE_ROUTE]: RIVAL_TYPE_BATTLE,
    [CLASSIFICATION_WAR_ROUTE]: RIVAL_TYPE_WAR,
};

export function renderBattleElo({importance, type}) {
    return importance === RIVAL_IMPORTANCE_RANKING && type === RIVAL_TYPE_BATTLE;
}

export function renderWarElo({importance, type}) {
    return importance === RIVAL_IMPORTANCE_RANKING && type === RIVAL_TYPE_WAR;
}

export function getElo(profile, type) {
    return profile[getEloProp(type)];
}

export function getEloProp(type) {
    if (type === RIVAL_TYPE_BATTLE) {
        return 'battleElo';
    } else if (type === RIVAL_TYPE_WAR) {
        return 'warElo';
    }
}

export function isRanking({importance}) {
    return importance === RIVAL_IMPORTANCE_RANKING;
}