export const WAR_STATUS_WAITING_FAST = 'WAITING_FAST';
export const WAR_STATUS_START_FAST = 'START_FAST';
export const WAR_STATUS_CANCELED_FAST = 'CANCELED_FAST';
export const WAR_STATUS_ERROR_FAST = 'ERROR_FAST';
export const WAR_STATUS_IN_PROGRESS = 'IN_PROGRESS';
export const WAR_STATUS_CLOSED = 'CLOSED';