export const WAITING_FOR_QUESTION = 'WAITING_FOR_QUESTION';
export const RECOGNIZING_QUESTION = 'RECOGNIZING_QUESTION';
export const THINKING = 'THINKING';

export const THINK_KNOW_ANSWER = 'THINK_KNOW_ANSWER';
export const LOOKING_FOR_ANSWER = 'LOOKING_FOR_ANSWER';

export const NO_FOUND_ANSWER_LOOKING_FOR = 'NO_FOUND_ANSWER_LOOKING_FOR';
export const FOUND_ANSWER_LOOKING_FOR = 'FOUND_ANSWER_LOOKING_FOR';

export const NOT_SURE_OF_ANSWER = 'NOT_SURE_OF_ANSWER';
export const RECOGNIZING_ANSWERS = 'RECOGNIZING_ANSWERS';

export const NOW_KNOW_ANSWER = 'NOW_KNOW_ANSWER';
export const DOESNT_KNOW_ANSWER = 'DOESNT_KNOW_ANSWER';

export const ANSWERED = 'ANSWERED';
export const SURRENDER = 'SURRENDER';

export const WILL_GIVE_RANDOM_ANSWER = 'WILL_GIVE_RANDOM_ANSWER';
export const WONT_GIVE_RANDOM_ANSWER = 'WONT_GIVE_RANDOM_ANSWER';

export const THINKING_WHICH_ANSWER_MATCH = 'THINKING_WHICH_ANSWER_MATCH';
export const THINKING_IF_GIVE_RANDOM_ANSWER = 'THINKING_IF_GIVE_RANDOM_ANSWER';

//no concentration
export const TALKING_ON_THE_PHONE = 'TALKING_ON_THE_PHONE';
export const WRITING_AN_SMS = 'WRITING_AN_SMS';
export const WOULD_EAT_SOMETHING = 'WOULD_EAT_SOMETHING';
export const DRINKING_JUICE = 'DRINKING_JUICE';
export const DREAMING_ABOUT_VACATION = 'DREAMING_ABOUT_VACATION';
export const SCRATCHING = 'SCRATCHING';
export const YAWNING = 'YAWNING';
export const HUMMING_A_SONG = 'HUMMING_A_SONG';
export const WATCHES_THE_AUDIENCE = 'WATCHES_THE_AUDIENCE';
export const HAS_MUSCLE_SPASM = 'HAS_MUSCLE_SPASM';
export const HUNG_UP = 'HUNG_UP';
export const NEED_GO_TO_TOILET = 'NEED_GO_TO_TOILET';

//skills
//hint
export const HINT_RECEIVED = 'HINT_RECEIVED';
export const THINKING_IF_USE_HINT = 'THINKING_IF_USE_HINT';
export const WILL_USE_HINT = 'WILL_USE_HINT';
export const WONT_USE_HINT = 'WONT_USE_HINT';
//waterPistol
export const WATER_PISTOL_USED_ON_IT = 'WATER_PISTOL_USED_ON_IT';
export const CLEANING = 'CLEANING';
//kidnapping
export const PREPARING_KIDNAPPING = 'PREPARING_KIDNAPPING';
export const TRYING_TO_KIDNAP = 'TRYING_TO_KIDNAP';
export const KIDNAPPING_SUCCEEDED = 'KIDNAPPING_SUCCEEDED';
export const KIDNAPPING_FAILED = 'KIDNAPPING_FAILED';
export const TRYING_TO_DEFEND = 'TRYING_TO_DEFEND';
export const WAS_KIDNAPPED = 'WAS_KIDNAPPED';
export const WAS_NOT_KIDNAPPED = 'WAS_NOT_KIDNAPPED';
export const CHANGING_CLOTHES = 'CHANGING_CLOTHES';
//ghost
export const PREPARING_DISGUISE = 'PREPARING_DISGUISE';
export const TRYING_TO_SCARE = 'TRYING_TO_SCARE';
export const SCARE_SUCCEEDED = 'SCARE_SUCCEEDED';
export const SCARE_FAILED = 'SCARE_FAILED';
export const REMOVING_DISGUISE = 'REMOVING_DISGUISE';
export const WAS_CAUGHT = 'WAS_CAUGHT';
export const WAS_NOT_CAUGHT = 'WAS_NOT_CAUGHT';
export const SCARING_ON_IT = 'SCARING_ON_IT';
export const RUN_AWAY = 'RUN_AWAY';
export const WAS_NOT_SCARED = 'WAS_NOT_SCARED';

