import _ from 'lodash';
import {APP_ROUTE, PROFILE_ROUTE, SETTINGS_CHOOSE_WISOR_ROUTE, SETTINGS_ROUTE, WISIES_ROUTE} from "../routes";

export const INTRO_STEP_WELCOME = 'INTRO_STEP_WELCOME';
export const INTRO_STEP_GO_TO_OPTIONS = 'INTRO_STEP_GO_TO_OPTIONS';
export const INTRO_STEP_OPTIONS = 'INTRO_STEP_OPTIONS';
export const INTRO_STEP_GO_TO_WISOR = 'INTRO_STEP_GO_TO_WISOR';
export const INTRO_STEP_WISOR = 'INTRO_STEP_WISOR';
export const INTRO_STEP_GO_TO_APP_FROM_OPTIONS = 'INTRO_STEP_GO_TO_APP_FROM_OPTIONS';
export const INTRO_STEP_GO_TO_WISIES = 'INTRO_STEP_GO_TO_WISIES';
export const INTRO_STEP_EXPERIMENT = 'INTRO_STEP_EXPERIMENT';
export const INTRO_STEP_NEW_WISIE = 'INTRO_STEP_NEW_WISIE';
export const INTRO_STEP_WISIE_DETAILS = 'INTRO_STEP_WISIE_DETAILS';

export const INTRO_STEP_GO_TO_PROFILE = 'INTRO_STEP_GO_TO_PROFILE';

export const STEP_ID_TO_NEXT_STEP_INDEX = {
    [INTRO_STEP_WELCOME]: 1,
    [INTRO_STEP_GO_TO_OPTIONS]: 2,
    [INTRO_STEP_OPTIONS]: 3,
    [INTRO_STEP_GO_TO_WISOR]: 4,
    [INTRO_STEP_WISOR]: 5,
    [INTRO_STEP_GO_TO_APP_FROM_OPTIONS]: 6,
    [INTRO_STEP_GO_TO_WISIES]: 7,
    [INTRO_STEP_EXPERIMENT]: 8,
    [INTRO_STEP_NEW_WISIE]: 9,
    [INTRO_STEP_WISIE_DETAILS]: 10,

    [INTRO_STEP_GO_TO_PROFILE]: 20,
};

export const STEP_ID_TO_ROUTE = {
    [INTRO_STEP_WELCOME]: APP_ROUTE,
    [INTRO_STEP_GO_TO_OPTIONS]: [APP_ROUTE, SETTINGS_ROUTE],
    [INTRO_STEP_OPTIONS]: SETTINGS_ROUTE,
    [INTRO_STEP_GO_TO_WISOR]: [SETTINGS_ROUTE, SETTINGS_CHOOSE_WISOR_ROUTE],
    [INTRO_STEP_WISOR]: [SETTINGS_CHOOSE_WISOR_ROUTE, SETTINGS_ROUTE],
    [INTRO_STEP_GO_TO_APP_FROM_OPTIONS]: [SETTINGS_ROUTE, APP_ROUTE],
    [INTRO_STEP_GO_TO_WISIES]: [APP_ROUTE, WISIES_ROUTE],
    [INTRO_STEP_EXPERIMENT]: WISIES_ROUTE,
    [INTRO_STEP_NEW_WISIE]: WISIES_ROUTE,
    [INTRO_STEP_WISIE_DETAILS]: WISIES_ROUTE,

    [INTRO_STEP_GO_TO_PROFILE]: [APP_ROUTE, PROFILE_ROUTE],
};

export const STEP_INDEX_TO_STEP_ID = _.reduce(STEP_ID_TO_NEXT_STEP_INDEX, (a, v, k) => {
    a[v - 1] = k;
    return a;
}, {});

export const INTRO_STEP_WELCOME_TEXT_0 = 'INTRO_STEP_WELCOME_TEXT_0';
export const INTRO_STEP_WELCOME_TEXT_1 = 'INTRO_STEP_WELCOME_TEXT_1';
export const INTRO_STEP_WELCOME_TEXT_2 = 'INTRO_STEP_WELCOME_TEXT_2';
export const INTRO_STEP_WELCOME_TEXT_3 = 'INTRO_STEP_WELCOME_TEXT_3';
export const INTRO_STEP_WELCOME_TEXT_4 = 'INTRO_STEP_WELCOME_TEXT_4';

export const INTRO_STEP_GO_TO_OPTIONS_TEXT_0 = 'INTRO_STEP_GO_TO_OPTIONS_TEXT_0';

export const INTRO_STEP_OPTIONS_TEXT_0 = 'INTRO_STEP_OPTIONS_TEXT_0';
export const INTRO_STEP_OPTIONS_TEXT_1 = 'INTRO_STEP_OPTIONS_TEXT_1';
export const INTRO_STEP_OPTIONS_TEXT_2 = 'INTRO_STEP_OPTIONS_TEXT_2';

export const INTRO_STEP_GO_TO_WISOR_TEXT_0 = 'INTRO_STEP_GO_TO_WISOR_TEXT_0';
export const INTRO_STEP_GO_TO_WISOR_TEXT_1 = 'INTRO_STEP_GO_TO_WISOR_TEXT_1';

export const INTRO_STEP_GO_TO_APP_FROM_OPTIONS_TEXT_0 = 'INTRO_STEP_GO_TO_APP_FROM_OPTIONS_TEXT_0';
export const INTRO_STEP_GO_TO_APP_FROM_OPTIONS_TEXT_1 = 'INTRO_STEP_GO_TO_APP_FROM_OPTIONS_TEXT_1';
export const INTRO_STEP_GO_TO_APP_FROM_OPTIONS_TEXT_2 = 'INTRO_STEP_GO_TO_APP_FROM_OPTIONS_TEXT_2';
export const INTRO_STEP_GO_TO_APP_FROM_OPTIONS_TEXT_3 = 'INTRO_STEP_GO_TO_APP_FROM_OPTIONS_TEXT_3';

export const INTRO_STEP_GO_TO_WISIES_TEXT_0 = 'INTRO_STEP_GO_TO_WISIES_TEXT_0';
export const INTRO_STEP_GO_TO_WISIES_TEXT_1 = 'INTRO_STEP_GO_TO_WISIES_TEXT_1';
export const INTRO_STEP_GO_TO_WISIES_TEXT_2 = 'INTRO_STEP_GO_TO_WISIES_TEXT_2';
export const INTRO_STEP_GO_TO_WISIES_TEXT_3 = 'INTRO_STEP_GO_TO_WISIES_TEXT_3';

export const INTRO_STEP_EXPERIMENT_TEXT_0 = 'INTRO_STEP_EXPERIMENT_TEXT_0';
export const INTRO_STEP_EXPERIMENT_TEXT_1 = 'INTRO_STEP_EXPERIMENT_TEXT_1';
export const INTRO_STEP_EXPERIMENT_TEXT_2 = 'INTRO_STEP_EXPERIMENT_TEXT_2';

export const INTRO_STEP_NEW_WISIE_TEXT_0 = 'INTRO_STEP_NEW_WISIE_TEXT_0';
export const INTRO_STEP_NEW_WISIE_TEXT_1 = 'INTRO_STEP_NEW_WISIE_TEXT_1';
export const INTRO_STEP_NEW_WISIE_TEXT_2 = 'INTRO_STEP_NEW_WISIE_TEXT_2';
export const INTRO_STEP_NEW_WISIE_TEXT_3 = 'INTRO_STEP_NEW_WISIE_TEXT_3';

export const INTRO_STEP_GO_TO_PROFILE_TEXT_0 = 'INTRO_STEP_GO_TO_PROFILE_TEXT_0';
